version: '3.7'

volumes:
  files:
    driver: local
  mysql:
    driver: local
  backup:
    driver: local
  redis:
    driver: local

services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud_server
    ports:
      - ${HTTP_PORT}:80
    depends_on:
      - mariadb
      - redis
    environment:
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_DOMAIN}
      - NEXTCLOUD_DATA_DIR=/srv/nextcloud/data
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-mariadb
      - REDIS_HOST=nextcloud-redis
    healthcheck:
      test: [ "CMD", "/usr/bin/healthcheck" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ${NEXTCLOUD_ROOT}/html:/var/www/html
      - ${NEXTCLOUD_ROOT}/data:/var/www/html/data
      - ./sensorlogger:/var/www/html/custom_apps/sensorlogger
    restart: always
    networks:
      - default

  mariadb:
    image: mariadb
    container_name: nextcloud_mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    command: [ "--max-allowed-packet=128M", "--innodb-log-file-size=64M", "--transaction-isolation=READ-COMMITTED", "--binlog-format=ROW", "--innodb-file-per-table=1", "--skip-innodb-read-only-compressed" ]
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-u", "root", "--password=nextcloud" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ${NEXTCLOUD_ROOT}/mariadb:/var/lib/mysql

  redis:
    image: redis
    container_name: nextcloud-redis
    restart: always
    command: ["--databases", "1"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis:/data